name: rho
dependencies:
  - python=3.11
  - pip
  - rust
  - cmake
  - pip:
    - ase
    - chemiscope
    - ipython
    - jupyter
    - jupyterlab
    - sympy
    - torch==2.1.0
    - wheel
    - wigners